services:
  redis:
    container_name: redis
    image: redis:8.0-alpine
    build:
        dockerfile: redis.Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

    networks:
      - net

  redis-insight:
    container_name: redis-insight
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data

    networks:
      - net

networks:
  net:

